language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libglib2.0-dev libpurple-dev libgcrypt-dev

script:
  - ./autogen.sh
  - ./configure && make && make lint
